### ISSUE TITLE
orya-font-asika

### ISSUE THREAD

**Issue by adplearn** [nlci/orya-font-asika#1]
It is NOT orya. IT IS "ORIYA" or "ODIA"

**Comment by jcoblentz** [comment]
[From the perspective of a font engineer] I think they are classifying their projects using the OpenType script tag. In this case it's "orya" for Odia script. See https://www.microsoft.com/typography/otspec/scripttags.htm for a list of script tags. Similarly, the ISO 15924 4-letter script code is "Orya".
